name = Ken Stimpson Front Layout
description = The front layout for the 2017 refresh.
preview = preview.png
template = front-layout

; Regions
regions[header] = Header
regions[banner] = Banner
regions[logo] = Logo
regions[banner_image] = Banner Image
regions[menu] = Menu
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[sidebar_second] = Second Sidebar
regions[bottom_first] = Bottom First Sidebar
regions[bottom_centre] = Bottom Centre
regions[bottom_second] = Bottom Second Sidebar
regions[footer] = Footer
regions[quote_1] = Quote 1

; Stylesheets
stylesheets[all][] = css/layouts/front/front.layout.css
stylesheets[all][] = css/layouts/front/front.layout.no-query.css
