name = Ken Stimpson Single Column Layout
description = A single column page most useful for when the page will be using panels.
preview = preview.png
template = singlecolumn-layout

; Regions
regions[header] = Header
regions[banner] = Banner
regions[logo] = Logo
regions[banner_image] = Banner Image
regions[menu] = Menu
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
;regions[sidebar_first] = First Sidebar
;regions[sidebar_second] = Second Sidebar
regions[bottom_first] = Bottom First Sidebar
regions[bottom_centre] = Bottom Centre
regions[bottom_second] = Bottom Second Sidebar
regions[footer] = Footer

; Stylesheets
stylesheets[all][] = css/layouts/singlecolumn/singlecolumn.layout.css
stylesheets[all][] = css/layouts/singlecolumn/singlecolumn.layout.no-query.css

; Plugins
plugins[panels][layouts] = panels/layouts
plugins[panels][styles] = panels/styles
